[main]
layout=Compact
theme=Nightshade
enable-touch-input=True
show-status-bar=False
start-minimized=False
xembed-onboard=False

[window]
window-state-sticky=True
force-to-top=True
window-decoration=False
docking-enabled=True
docking-edge=bottom
disable-in-fullscreen=False
transparency=0.0
enable-inactive-transparency=False

[auto-show]
enabled=False

[keyboard]
show-click-buttons=False
touch-feedback-enabled=True
